### ISSUE TITLE
Merger script suggestion: Include schemaVersion for the class

### ISSUE THREAD

**Issue by gtsueng** [BioSchemas/bioschemas-dde#1]
Something like this: 
![image](https://user-images.githubusercontent.com/9200138/141152847-4279c3ae-0a07-4a99-8138-140cf4a822be.png)

Note that since the schemaVersion may have several parents, use an array/list

**Comment by AlasdairGray** [comment]
As discussed during our meeting, we should also track the Schema.org version number. I think we are looking at something like:
```json
{
  "@context": {
    "schema": "http://schema.org/",
    "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
    "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
    "bioschemas": "http://discovery.biothings.io/view/bioschemas/"
  },
  "@graph": [
    {
      "@id": "bioschemas:ComputationalTool",
      "@type": "rdfs:Class",
      "schema:schemaVersion": ["https://bioschemas.org/profiles/ComputationalTool/1.0-RELEASE", "https://schema.org/docs/releases.html#v13.0"],
      "rdfs:comment": "The Life Science Tools specification provides a way to describe bioscience tools and software on the World Wide Web. It defines a set of metadata and vocabularies, built on top of existing technologies and standards, that can be used to represent such tools in Web pages and applications. The goal of the specification is to make it easier to discover. Version 1.0-RELEASE.",
      "rdfs:label": "ComputationalTool",
      "rdfs:subClassOf": {
        "@id": "schema:SoftwareApplication"
      },
```

Note I'm using ComputationalTool as this has a profile (we don't have a profile for BioChemEntity, we see it as an abstract class).

I've guessed at the IRI for the schema.org version.

**Comment by gtsueng** [comment]
The merger script should now automatically append the bioschema version. The schema.org version should be added to classes via the DDE, so I'll make a note of it in the issue there.
