### ISSUE TITLE
Authorozitaions required by DDE when logging in with Github credentials

### ISSUE THREAD

**Issue by frmichel** [BioSchemas/bioschemas-dde#2]
When I log in with my Github credentials, DDE requests write access to all of my repositories, beyond just Bioschemas related repos.
Would be better to have it request only authorizations related to my clones of Bioschemas repos. If possible.
Thx.

**Comment by gtsueng** [comment]
Please post the issue to the actual Data Discovery Engine's repository: https://github.com/biothings/discovery-app.  This repository is just for a script for converting/merging bioschemas specifications for ingestion into the DDE.

**Comment by frmichel** [comment]
Indeed, sorry about that. It's done https://github.com/biothings/discovery-app/issues/131
